input: doc
output: _build
requirements: requirements.txt
target: gh-pages
formats: [ html ]
images:
  base: btdi/sphinx:vhdldomain
theme: https://codeload.github.com/buildthedocs/sphinx.theme/tar.gz/v1
