.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:VHDLDomain-github| image:: https://img.shields.io/badge/VHDL-VHDLDomain-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain
.. |SHIELD:png:VHDLDomain-github| image:: https://raster.shields.io/badge/VHDL-VHDLDomain-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain

.. # Sourcecode license
.. |SHIELD:svg:VHDLDomain-src-license| image:: https://img.shields.io/pypi/l/VHDLDomain?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: License.html
.. |SHIELD:png:VHDLDomain-src-license| image:: https://img.shields.io/pypi/l/VHDLDomain?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/VHDL/VHDLDomain/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:VHDLDomain-tag| image:: https://img.shields.io/github/v/tag/vhdl/VHDLDomain?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain/tags
.. |SHIELD:png:VHDLDomain-tag| image:: https://raster.shields.io/github/v/tag/vhdl/VHDLDomain?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain/tags

.. # GitHub release date
.. |SHIELD:svg:VHDLDomain-date| image:: https://img.shields.io/github/release-date/vhdl/VHDLDomain?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain/releases
.. |SHIELD:png:VHDLDomain-date| image:: https://raster.shields.io/github/release-date/vhdl/VHDLDomain?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:VHDLDomain-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/VHDLDomain?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain/network/dependents
.. |SHIELD:png:VHDLDomain-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/VHDLDomain?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/vhdl/VHDLDomain/network/dependents

.. # GHA workflow
.. |SHIELD:svg:VHDLDomain-gha-test| image:: https://img.shields.io/github/actions/workflow/status/vhdl/VHDLDomain/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/VHDL/VHDLDomain/actions/workflows/Pipeline.yml
.. |SHIELD:png:VHDLDomain-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/vhdl/VHDLDomain/Pipeline.yml?branch=main&longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/VHDL/VHDLDomain/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:VHDLDomain-codacy-quality| image:: https://img.shields.io/codacy/grade/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/vhdl/VHDLDomain
.. |SHIELD:png:VHDLDomain-codacy-quality| image:: https://raster.shields.io/codacy/grade/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/vhdl/VHDLDomain

.. # Codacy - coverage
.. |SHIELD:svg:VHDLDomain-codacy-coverage| image:: https://img.shields.io/codacy/coverage/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/vhdl/VHDLDomain
.. |SHIELD:png:VHDLDomain-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/2286426d2b11417e90010427b7fed8e7?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/vhdl/VHDLDomain

.. # Codecov - coverage
.. |SHIELD:svg:VHDLDomain-codecov-coverage| image:: https://img.shields.io/codecov/c/github/vhdl/VHDLDomain?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/vhdl/VHDLDomain
.. |SHIELD:png:VHDLDomain-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/vhdl/VHDLDomain?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/vhdl/VHDLDomain

.. # Libraries - source rank
.. |SHIELD:svg:VHDLDomain-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/VHDLDomain?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/vhdl/VHDLDomain/sourcerank
.. |SHIELD:png:VHDLDomain-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/VHDLDomain?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/vhdl/VHDLDomain/sourcerank

.. # PyPI tag
.. |SHIELD:svg:VHDLDomain-pypi-tag| image:: https://img.shields.io/pypi/v/VHDLDomain?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/VHDLDomain/
.. |SHIELD:png:VHDLDomain-pypi-tag| image:: https://raster.shields.io/pypi/v/VHDLDomain?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/VHDLDomain/

.. # PyPI project status
.. |SHIELD:svg:VHDLDomain-pypi-status| image:: https://img.shields.io/pypi/status/VHDLDomain?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:VHDLDomain-pypi-status| image:: https://raster.shields.io/pypi/status/VHDLDomain?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:VHDLDomain-pypi-python| image:: https://img.shields.io/pypi/pyversions/VHDLDomain?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:VHDLDomain-pypi-python| image:: https://raster.shields.io/pypi/pyversions/VHDLDomain?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:VHDLDomain-lib-status| image:: https://img.shields.io/librariesio/release/pypi/VHDLDomain?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/vhdl/VHDLDomain
.. |SHIELD:png:VHDLDomain-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/VHDLDomain?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/vhdl/VHDLDomain

.. # Documentation license
.. |SHIELD:svg:VHDLDomain-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:VHDLDomain-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/VHDL/VHDLDomain/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:VHDLDomain-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=vhdl.github.io%2FVHDLDomain&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fvhdl.github.io%2FVHDLDomain%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://vhdl.github.io/VHDLDomain/
.. |SHIELD:png:VHDLDomain-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=vhdl.github.io%2FVHDLDomain&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fvhdl.github.io%2FVHDLDomain%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://vhdl.github.io/VHDLDomain/

.. # Gitter
.. |SHIELD:svg:VHDLDomain-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:VHDLDomain-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
